### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by pdxbmw** [VladShcherbin/meteor-flex-grid#1]
I've been trying to look at examples on your website, but keep getting prompted for credentials on the root page. Is the site down? Is there somewhere else to see documentation?

**Comment by VladShcherbin** [comment]
Hey, I'm changing the hosting provider, it should be up within 48 hours.

**Comment by pdxbmw** [comment]
Okay, great. Thank you for the response.

**Comment by VladShcherbin** [comment]
Okay, the new hosting is working and everything seems to be okay.

Sorry for the inconvenience, thought no one is using it.

**Comment by Birssan** [comment]
Down again ?
